spring:
  datasource:
    url: jdbc:mysql://servicestationdbdev.czntefjg545i.eu-west-2.rds.amazonaws.com:3306/serviceStationDbDev?useSSL=false
    username: adminfranek
    password: korelacja
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oagx35io5c2hxOFm356
            client-secret: zwzuA1OoQAqHy3sDkva9hQQZwcaaqWcNvZzPMemc
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: https://dev-495086.okta.com/oauth2/default